---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-dx-t480s
# description will be included in the image's metadata
description: bluefin-dx with customization for ThinkPad t480s

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/python-validity/repo/fedora-%OS_VERSION%/sneexy-python-validity-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/lazygit/repo/fedora-41/atim-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-41/pgdev-ghostty-fedora-%OS_VERSION%.repo
    install:
      - starship
      # Install t480s compatible fprint
      - open-fprintd
      - fprintd-clients
      - fprintd-clients-pam
      - python3-validity
      # Install modem-manager
      - modem-manager-gui
      - modem-manager-gui-cm-NetworkManager
      # Install Dev Tools
      - ghostty
      - gh
      - syncthing
      - lazygit
    remove:
      # Remove t480s incompatible fprint
      - fprintd
      - fprintd-pam

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        install:
          - org.gnome.Loupe
          - io.github.dvlv.boxbuddyrs
          - com.github.rafostar.Clapper
          - org.fedoraproject.MediaWriter
          - com.github.tchx84.Flatseal
          - io.github.flattool.Ignition
          - io.github.flattool.Warehouse
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.DejaDup
          - org.gnome.Papers
          - com.mattjakeman.ExtensionManager
          - org.gnome.FileRoller
          - org.gnome.font-viewer
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.World.PikaBackup
          - org.gnome.TextEditor
          - org.gnome.Weather
          - io.missioncenter.MissionCenter
          - io.podman_desktop.PodmanDesktop
        remove:
          - org.gnome.eog
      - notify: true
        scope: user # Also add Flathub user repo, but no user packages
        install:
          - app.zen_browser.zen
          - dev.zed.Zed

  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - open-fprintd-resume.service
        - open-fprintd-suspend.service
        - open-fprintd.service
        - python3-validity.service

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Caffeine
      - Tiling Shell
      - Wiggle

  - type: justfiles

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
